---
- hosts: hw1
  remote_user: ubuntu
  become: yes
  tasks:
  - name: update
    raw: sudo apt update
  - name: install py2
    apt:
      name: python
  - name: install apache
    apt:
      name: apache2
  - name: git clone
    git:
      repo: https://github.com/enrui-shi/cse356
      dest: ver/www/html
